name: szu-net
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - expat=2.7.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - nodejs=25.2.1
  - openssl=3.6.0
  - pip=25.3
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - idna==3.11
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - pillow==12.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-settings==2.0.3
      - pyexecjs==1.5.1
      - pygments==2.19.2
      - pystray==0.19.5
      - python-dotenv==1.0.1
      - pywin32==311
      - requests==2.31.0
      - rich==14.2.0
      - six==1.17.0
      - ttkbootstrap==1.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.2
      - win32-setctime==1.2.0
prefix: C:\Users\Aaten77\.conda\envs\szu-net
